# Generated by Django 2.0.7 on 2018-08-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=64)),
                ('destinations', models.CharField(max_length=64)),
                ('duration', models.CharField(max_length=64)),
            ],
        ),
    ]
